version: "3"

services:
  server-1:
    build:
      context: server-1
    ports:
      - "3001:80"
  server-2:
    build:
      context: server-2
    ports:
      - "3002:80"
  server-3:
    build:
      context: server-3
    ports:
      - "3003:3003"
